#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#

SUBDIRECTORY_OK=1
USAGE="[options] <parent>"
LONG_USAGE="    Options:
        -h          Display this message
        -m <msg>    Use this as message
        -s          Add a 'Signed-off-by' line
        -S          Sign the issue with GPG (unimplemented)
        -t          Use a temporary file instead of .git/COMMIT_EDITMSG
        -Q          Quote parent
        -r <commit> Reference the commit or message supplied

Reply to a specific message in an issue."

. "$(git --exec-path)/git-sh-setup"


MESSAGE=""
SIGNOFF=0
GPGSIGN=0
USE_TEMPFILE=0
QUOTE=0
PARENT=""
ADDITIONAL_PARENTS=()

while getopts "hm:sStQr:" OPT
do
  case $OPT in

    h)
        usage
        exit 0
        ;;

    m)
        MESSAGE="$OPTARG"
        ;;

    s)
        SIGNOFF=1
        ;;

    S)
        GPGSIGN=1
        ;;

    t)
        USE_TEMPFILE=1
        ;;

    Q)
        QUOTE=1
        ;;

    r)
        ADDITIONAL_PARENTS+=("$OPTARG")
        ;;

    *)
        die "Option does not exist: $OPT" #TODO: fix
        ;;

  esac
done
shift $(($OPTIND-1))

PARENT="$1"
INIT_HASH="$(git dit find-tree-init-hash "$PARENT")"

[[ -z "$PARENT" ]] && die "No parent"

TMPFILE="$GIT_DIR/COMMIT_EDITMSG"
if [[ $USE_TEMPFILE -eq 1 ]]; then
    TMPFILE="$(mktemp)"
fi

git rev-list --format="Re: %s%n" -n 1 "$INIT_HASH" | tail -n+2 > $TMPFILE

if [[ $QUOTE -eq 1 ]]; then
    git rev-list --format="%b" -n 1 "$PARENT" | tail -n+2 | \
        sed +'s,^,> ,;s, *$,,' >> $TMPFILE
fi

# Executes git-interpret-trailer on $2 if $1 is -eq 1
signoff() {
    [[ $1 -eq 1 ]] && \
        git interpret-trailers \
            --in-place \
            --trailer \
            "Signed-off-by=$(git config user.name) <$(git config user.email)>" \
            $2
}

if [[ -z "$MESSAGE" ]]; then
    signoff "$SIGNOFF" "$TMPFILE"
    $EDITOR $TMPFILE
else
    echo "$MESSAGE" >> $TMPFILE
    signoff "$SIGNOFF" "$TMPFILE"
fi

cat "$TMPFILE" | git dit check-message || \
    die "The format of the provided message is faulty"

cat $TMPFILE | git stripspace -s | \
    git dit create-message \
        -i "$INIT_HASH" \
        "$PARENT" \
        "${ADDITIONAL_PARENTS[@]}" \
        >> /dev/null

rm $TMPFILE

