#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#
# $(basename $0) [options]
#
# (c) 2016 Matthias Beyer, Julian Ganz

abort() {
    echo "$*" >&2
    exit 1
}

SUBDIRECTORY_OK=1
USAGE="[options]"
LONG_USAGE="    Options:
        -h          Display this message
        -a          Abbreviate issue hash
        -l          List long (not one line per issue, executes 'git dit show'
                    on each issue)
        -n <n>      List only <n> issues

List issues.

Issues are listed in the following form:

    <hash> (<date when the issue was added, human readable>) <header line>

More functionality may come and the output format may change."

. "$(git --exec-path)/git-sh-setup"


ABBREV=0
LONG=0
__N=

while getopts "haln:" opt
do
  case $opt in

    h)
        usage
        exit 0
        ;;

    a)
        ABBREV=1
        ;;

    l)
        LONG=1
        ;;

    n)
        __N=$OPTARG
        ;;

    *)
        echo -e "\n  Option does not exist : $OPTARG\n"
        usage
        exit 1
        ;;

  esac
done
shift $(($OPTIND-1))

FORMAT="%ct "
[[ $ABBREV -eq 1 ]] && FORMAT+="%h" || FORMAT+="%H"

FORMAT+=" (%ar) %s"

#
# Get all issue-tree-init hashes, and for each of them call the `git show`
# command to show them, with a format which is a one-line format.
# Afterwards sort them by date, and filter them accordingly to the user flags:
#
git dit get-issue-tree-init-hashes | while read hash; do
    git --no-pager show --format="$FORMAT" "$hash"
done | sort -n --reverse | uniq | cut -d " " -f 2- | \
    if [[ -z "$__N" ]]; then
        cat # simply print everything
    else
        head -n $__N # Only print N lines
    fi |\
    if [[ $LONG -eq 1 ]]; then # if the user wants all the things shown
        cut -d " " -f 1 | \
            while read hash; do # fetch the hash again from the listing
                # and call fancy `show`
                git --no-pager dit show -I "$hash"; echo;
            done | \
            $(git var GIT_PAGER) # eventually with the git pager
    else
        cat # if the user does not want all the things, cat
    fi

