#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#

SUBDIRECTORY_OK=1
USAGE="<remote> [issue-hash]..."
LONG_USAGE="

Push all refs associated with issues.
If no issue were supplied, all issues will be pushed."

. "$(git --exec-path)/git-sh-setup"


REMOTE="$1"
shift

[[ -z "$REMOTE" ]] && die "No remote supplied"

get_issue_refs() {
    for issue in $@; do
        git for-each-ref "refs/dit/**" --contains "$issue" | \
            sed -r "+s/^[[:alnum:]]+ +commit\t([^[:space:]]+)$/\\1/"
    done
}

ISSUES=$@
if [[ $# -eq 0 ]]; then
    ISSUES=$(git dit get-issue-tree-init-hashes)
fi

exec git push "$REMOTE" $(get_issue_refs $ISSUES)

