#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#
# $(basename $0) <metadata key-value-pairs...>
#
# (c) 2016 Matthias Beyer, Julian Ganz

#for i in "$@"; do echo "$i"; done >&2

args=()
for i in "$@"; do
    args+=("--trailer" "Dit-$i")
done

if [[ -z "$DIT_PREPARE_META_INPLACE" ]]; then
    git interpret-trailers "${args[@]}"
else
    git interpret-trailers --in-place "${args[@]}" "$DIT_PREPARE_META_INPLACE"
fi

