#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#
# $(basename $0) <metadata key-value-pairs...>
#
# (c) 2016 Matthias Beyer, Julian Ganz

if [[ -z "$DIT_PREPARE_META_INPLACE" ]]; then
    git interpret-trailers $(for arg; do echo "--trailer" "Dit-$arg"; done)
else
    git interpret-trailers --in-place \
        $(for arg; do echo "--trailer" "Dit-$arg"; done) \
        "$DIT_PREPARE_META_INPLACE"
fi

