#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#
# Lists all SHA1 hashes of all issues (introducing commit)
#
# (c) 2016 Matthias Beyer, Julian Ganz
#

git for-each-ref "refs/remotes/*/dit/*/head" "refs/dit/*/head" | \
    sed -r 's,.*refs/remotes/.*/(.*)/head,\1,'

