#!/usr/bin/env bash
#
#   git-dit - the distributed issue tracker for git
#   Copyright (C) 2016 Matthias Beyer <mail@beyermatthias.de>
#   Copyright (C) 2016 Julian Ganz <neither@nut.email>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
# -----
#
# $(basename $0) [<file>]
# Arguments:
#  $1 - path to file
#
# This command checks the message in file for validity
#
# (c) 2016 Matthias Beyer, Julian Ganz

abort() {
    echo "$*" >&2
    exit 1
}

git stripspace -s | {
    # the first line must contain the subject
    read line && [[ -n "$line" ]] || exit 1
    # if the commit has more than one line, the second line must be empty
    if read line; then
        [[ -z "$line" ]] || exit 1
    fi
}

